### ISSUE TITLE
Profile: Saving - Funding

### ISSUE THREAD

**Issue by brandinalexander** [unicef/un-partner-portal#823]
Ticket:
https://trello.com/c/B0M7IsP5/170-profile-saving

**Comment by mjaworski** [comment]
This was most likely fixed with https://github.com/unicef/un-partner-portal/pull/858

**Comment by brandinalexander** [comment]
Still showing an error message. Please see comments in Trello Ticket.

**Comment by brandinalexander** [comment]
Asked client to follow up on the source of budgets for Country Partners. (Individual, HQ, or Both)

**Comment by mjaworski** [comment]
Moving to done, work continues in #902
